name: zer0kcal
description: "제로칼로리"
publish_to: 'none'
version: 1.0.1+2
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  cloud_firestore: ^5.6.6
  go_router: ^14.8.1
  shorebird_code_push: ^2.0.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  intl: ^0.20.2
  logger: ^2.5.0
  dio: ^5.8.0+1
  adaptive_dialog: ^2.4.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_vertexai: ^1.5.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  share_plus: ^10.1.4
  screenshot: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh_flutter3: ^2.0.2
  rename_app: ^1.6.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  custom_lint: ^0.7.5
  freezed_lint: ^0.0.9
  flutter_launcher_icons: "^0.14.3"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
  fonts:
    - family: BMEULJIROTTF
      fonts:
        - asset: assets/fonts/BMEULJIROTTF.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"