name: zer0kcal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  cloud_firestore: ^5.6.6
  go_router: ^14.8.1
  shorebird_code_push: ^2.0.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  intl: ^0.20.2
  logger: ^2.5.0
  dio: ^5.8.0+1
  adaptive_dialog: ^2.4.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_vertexai: ^1.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: BMEULJIROTTF
      fonts:
        - asset: assets/fonts/BMEULJIROTTF.ttf